apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cakeapi
    type: reinventdemo
  name: cakeapi
  namespace: cakeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cakeapi
      type: reinventdemo
  template:
    metadata:
      labels:
        app: cakeapi
        type: reinventdemo
    spec:
      serviceAccountName: i-am-here-now
      containers:
      - image: 081324788528.dkr.ecr.us-east-1.amazonaws.com/cakeapi:6-fixProbes
        name: cakeapi
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: TABLENAME
          value: "cakeType"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 60Mi
          limits:
            cpu: 50m
            memory: 70Mi
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/logmeforever.txt
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30

