apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: morecakeplease
  namespace: cakeapi
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cakeapi
  targetCPUUtilizationPercentage: 40
