apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cakeapi
    type: demoApp
  name: cakeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cakeapi
  template:
    metadata:
      labels:
        app: cakeapi
    spec:
      serviceAccountName: serviceaccount
      containers:
      - image: 081324788528.dkr.ecr.us-east-1.amazonaws.com/cakeapi:5
        name: cakeapi
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: TABLENAME
          value: "thirudynamotable"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 100m
          limits:
            cpu: 100m
            memory: 200m
        livenessProbe:
          exec:
            command:
            - curl
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30

