apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 3
  disableIMDSv1: true
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: false
      appMeshPreview: false
      autoScaler: false
      awsLoadBalancerController: false
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  instanceType: t4g.medium
  labels:
    alpha.eksctl.io/cluster-name: minas-tirith
    alpha.eksctl.io/nodegroup-name: ng-bf135a52
  maxPodsPerNode: 100
  maxSize: 3
  minSize: 3
  name: ng-bf135a52
  privateNetworking: false
  releaseVersion: ""
  securityGroups:
    withLocal: null
    withShared: null
  ssh:
    allow: false
    publicKeyPath: ""
  subnets:
  - 
  tags:
    alpha.eksctl.io/nodegroup-name: ng-bf135a52
    alpha.eksctl.io/nodegroup-type: managed
  volumeIOPS: 3000
  volumeSize: 80
  volumeThroughput: 125
  volumeType: gp3
metadata:
  name: minas-tirith
  region: us-east-1
  version: "1.27"
